module.exports = {
    PROPERTY_TYPES: {
        "All suite": "All suite",
        "All-Inclusive resort": "All-Inclusive resort",
        "Apartment": "Apartment",
        "Bed and breakfast": "Bed and breakfast",
        "Chalet": "Chalet",
        "Condominium": "Condominium",
        "Guest house": "Guest house",
        "Hotel": "Hotel",
        "Lodge": "Lodge",
        "Resort": "Resort",
        "Vacation home": "Vacation home",
        "Villa": "Villa",
        "Castle": "Castle",
        "Aparthotel": "Aparthotel",
        "Boat": "Boat",
        "Cottage": "Cottage",
        "Camping": "Camping",
        "House": "House",
        "Private room in apartment": "Private room in apartment",
        "Shared room": "Shared room",
        "Cabin": "Cabin",
        "Bungalow": "Bungalow",
        "Riad": "Riad",
        "Recreational vehicle": "Recreational vehicle",
        "Ryokan": "Ryokan",
        "Loft": "Loft",
        "Townhouse": "Townhouse",
    },
    PROPERTY_FLOORS: [
        { "id": "Basement", "name": "Basement" },
        { "id": "Ground", "name": "Ground" },
        { "id": "1", "name": "1" },
        { "id": "2", "name": "2" },
        { "id": "3", "name": "3" },
        { "id": "4", "name": "4" },
        { "id": "5", "name": "5" },
        { "id": "6", "name": "6" },
        { "id": "7", "name": "7" },
        { "id": "8", "name": "8" },
        { "id": "9", "name": "9" },
        { "id": "10", "name": "10" },
        { "id": "11", "name": "11" },
        { "id": "12", "name": "12" },
        { "id": "13", "name": "13" },
        { "id": "14", "name": "14" },
        { "id": "15", "name": "15" },
        { "id": "16", "name": "16" },
        { "id": "17", "name": "17" },
        { "id": "18", "name": "18" },
        { "id": "19", "name": "19" },
        { "id": "20", "name": "20" },
    ],
    AMENITIES: {
        "Hair Dryer": "Hair Dryer",
        "Central Heating": "Central Heating",
        "Washing Machine": "Washing Machine",
        "Cable TV": "Cable TV",
        "TV": "TV",
        "internet connection": "internet connection",
        "Bed Linen": "Bed Linen",
        "Dryer": "Dryer",
        "Billiards / Pool Tables": "Billiards / Pool Tables",
        "Golf": "Golf",
        "No Pets Allowed": "No Pets Allowed",
        "Cross Country Skiing": "Cross Country Skiing",
        "Snowboarding": "Snowboarding",
        "Smoke Detectors": "Smoke Detectors",
        "Parking": "Parking",
        "garage": "garage",
        "Suitable for children": "Suitable for children",
        "Family friendly": "Family friendly",
        "Carbon Monoxide Detector": "Carbon Monoxide Detector",
        "shopping": "shopping",
        "hiking biking nearby": "hiking biking nearby",
        "mountain climbing nearby": "mountain climbing nearby",
        "sledding nearby": "sledding nearby",
        "snowmobiling nearby": "snowmobiling nearby",
        "Smoking not allowed": "Smoking not allowed",
        "Disinfectants used for cleaning": "Disinfectants used for cleaning",
        "Contactless check-in and checkout is available.": "Contactless check-in and checkout is available.",
        "Living room": "Living room",
        "Fireplace": "Fireplace",
        "Towels": "Towels",
        "Dishwasher": "Dishwasher",
        "kettle": "kettle",
        "Cookware  Kitchen Utensils": "Cookware  Kitchen Utensils",
        "cooking hob": "cooking hob",
        "oven": "oven",
        "microwave": "microwave",
        "toaster": "toaster",
        "fridge / freezer": "fridge / freezer",
        "freezer": "freezer",
        "air conditioning": "air conditioning",
        "sofa": "sofa",
        "heating": "heating",
        "stove": "stove",
        "Free Wireless Internet": "Free Wireless Internet",
        "Ice Maker": "Ice Maker",
        "blender": "blender",
        "Ironing Board": "Ironing Board",
        "Pets are welcome": "Pets are welcome",
        "Heating": "Heating",
        "Outdoor Parking": "Outdoor Parking",
        "Waterfront": "Waterfront",
        "Near ocean": "Near ocean",
        "Laptop workspace": "Laptop workspace",
        "Gym": "Gym",
        "No parties": "No parties",
        "Water View": "Water View",
        "Fire Extinguisher": "Fire Extinguisher",
        "outdoor furniture": "outdoor furniture",
        "dining room seats": "dining room seats",
        "Property is vacant for at least 24 hours between reservations.": "Property is vacant for at least 24 hours between reservations.",
        "Ceiling Fan": "Ceiling Fan",
        "Coffee Maker in Room": "Coffee Maker in Room",
        "Elevator": "Elevator",
        "Free Parking": "Free Parking",
        "No Smoking Rooms/Facilities": "No Smoking Rooms/Facilities",
        "garden": "garden",
        "river": "river",
        "Downtown": "Downtown",
        "private entrance": "private entrance",
        "Drying Rack": "Drying Rack",
        "Balcony": "Balcony",
        "Terrace": "Terrace",
        "gas/electric hob": "gas/electric hob",
        "radio": "radio",
        "swimming pool": "swimming pool",
        "BBQ grill": "BBQ grill",
        "High speed Internet access": "High speed Internet access",
        "dining room": "dining room",
        "chairs": "chairs",
        "Restaurant": "Restaurant",
        "Boating": "Boating",
        "Fishing": "Fishing",
        "Free Local Telephone Calls": "Free Local Telephone Calls",
        "Heated Pool": "Heated Pool",
        "Outdoor Pool": "Outdoor Pool",
        "Shopping Mall": "Shopping Mall",
        "Outdoor Tennis": "Outdoor Tennis",
        "Local hospital": "Local hospital",
        "Smart TV": "Smart TV",
        "Patio": "Patio",
        "External Lighting": "External Lighting",
        "beach towels": "beach towels",
        "Iron  Ironing Board": "Iron  Ironing Board",
        "Bed Linen  Towels": "Bed Linen  Towels",
        "High Chairs": "High Chairs",
        "single bed": "single bed",
        "Queen size bed": "Queen size bed",
        "Private parking": "Private parking",
        "Wireless Internet": "Wireless Internet",
        "Communal pool": "Communal pool",
        "full kitchen": "full kitchen",
        "Hot Tub": "Hot Tub",
        "Game room": "Game room",
        "Concierge": "Concierge",
        "Mountain View": "Mountain View",
        "Spa": "Spa",
        "Massage": "Massage",
        "Private pool": "Private pool",
        "Breakfast booking possible": "Breakfast booking possible",
        "Veranda": "Veranda",
        "Housekeeping service": "Housekeeping service",
        "leisure gambling": "leisure gambling",
        "first aid kit": "first aid kit",
        "accommodations other services car available": "accommodations other services car available",
        "romantic property theme": "romantic property theme",
        "Enhanced cleaning practices": "Enhanced cleaning practices",
        "Linen and towels washed in at least 60°C/140°F": "Linen and towels washed in at least 60°C/140°F",
        "Stereo": "Stereo",
        "Fitness Room": "Fitness Room",
        "Sauna": "Sauna",
        "wifi": "wifi",
        "pool": "pool",
        "Iron": "Iron",
        "Doorman": "Doorman",
        "Refrigerator": "Refrigerator",
        "Family/kids friendly": "Family/kids friendly",
        "location beachfront": "location beachfront",
        "High touch surfaces disinfected": "High touch surfaces disinfected",
        "washer - common space": "washer - common space",
        "dryer - common space": "dryer - common space",
        "Kitchen": "Kitchen",
        "coffee maker": "coffee maker",
        "Crockery  Cutlery": "Crockery  Cutlery",
        "Internet": "Internet",
        "Packing": "Packing",
        "Baby cot": "Baby cot",
        "Swimming Pool": "Swimming Pool",
        "Washing machine": "Washing machine",
        "Linen & towels": "Linen & towels",
        "Satellite TV": "Satellite TV",
        "Garden": "Garden",
        "Iron and Ironing board": "Iron and Ironing board",
        "Air Conditioning": "Air Conditioning"
    },
    COUNTRIES: [
        { code: "AD", label: "Andorra", phone: "376" },
        {
            code: "AE",
            label: "United Arab Emirates",
            phone: "971",
        },
        { code: "AF", label: "Afghanistan", phone: "93" },
        {
            code: "AG",
            label: "Antigua and Barbuda",
            phone: "1-268",
        },
        { code: "AI", label: "Anguilla", phone: "1-264" },
        { code: "AL", label: "Albania", phone: "355" },
        { code: "AM", label: "Armenia", phone: "374" },
        { code: "AO", label: "Angola", phone: "244" },
        { code: "AQ", label: "Antarctica", phone: "672" },
        { code: "AR", label: "Argentina", phone: "54" },
        { code: "AS", label: "American Samoa", phone: "1-684" },
        { code: "AT", label: "Austria", phone: "43" },
        {
            code: "AU",
            label: "Australia",
            phone: "61",
            suggested: true,
        },
        { code: "AW", label: "Aruba", phone: "297" },
        { code: "AX", label: "Alland Islands", phone: "358" },
        { code: "AZ", label: "Azerbaijan", phone: "994" },
        {
            code: "BA",
            label: "Bosnia and Herzegovina",
            phone: "387",
        },
        { code: "BB", label: "Barbados", phone: "1-246" },
        { code: "BD", label: "Bangladesh", phone: "880" },
        { code: "BE", label: "Belgium", phone: "32" },
        { code: "BF", label: "Burkina Faso", phone: "226" },
        { code: "BG", label: "Bulgaria", phone: "359" },
        { code: "BH", label: "Bahrain", phone: "973" },
        { code: "BI", label: "Burundi", phone: "257" },
        { code: "BJ", label: "Benin", phone: "229" },
        { code: "BL", label: "Saint Barthelemy", phone: "590" },
        { code: "BM", label: "Bermuda", phone: "1-441" },
        { code: "BN", label: "Brunei Darussalam", phone: "673" },
        { code: "BO", label: "Bolivia", phone: "591" },
        { code: "BR", label: "Brazil", phone: "55" },
        { code: "BS", label: "Bahamas", phone: "1-242" },
        { code: "BT", label: "Bhutan", phone: "975" },
        { code: "BV", label: "Bouvet Island", phone: "47" },
        { code: "BW", label: "Botswana", phone: "267" },
        { code: "BY", label: "Belarus", phone: "375" },
        { code: "BZ", label: "Belize", phone: "501" },
        {
            code: "CA",
            label: "Canada",
            phone: "1",
            suggested: true,
        },
        {
            code: "CC",
            label: "Cocos (Keeling) Islands",
            phone: "61",
        },
        {
            code: "CD",
            label: "Congo, Democratic Republic of the",
            phone: "243",
        },
        {
            code: "CF",
            label: "Central African Republic",
            phone: "236",
        },
        {
            code: "CG",
            label: "Congo, Republic of the",
            phone: "242",
        },
        { code: "CH", label: "Switzerland", phone: "41" },
        { code: "CI", label: "Cote d'Ivoire", phone: "225" },
        { code: "CK", label: "Cook Islands", phone: "682" },
        { code: "CL", label: "Chile", phone: "56" },
        { code: "CM", label: "Cameroon", phone: "237" },
        { code: "CN", label: "China", phone: "86" },
        { code: "CO", label: "Colombia", phone: "57" },
        { code: "CR", label: "Costa Rica", phone: "506" },
        { code: "CU", label: "Cuba", phone: "53" },
        { code: "CV", label: "Cape Verde", phone: "238" },
        { code: "CW", label: "Curacao", phone: "599" },
        { code: "CX", label: "Christmas Island", phone: "61" },
        { code: "CY", label: "Cyprus", phone: "357" },
        { code: "CZ", label: "Czech Republic", phone: "420" },
        {
            code: "DE",
            label: "Germany",
            phone: "49",
            suggested: true,
        },
        { code: "DJ", label: "Djibouti", phone: "253" },
        { code: "DK", label: "Denmark", phone: "45" },
        { code: "DM", label: "Dominica", phone: "1-767" },
        {
            code: "DO",
            label: "Dominican Republic",
            phone: "1-809",
        },
        { code: "DZ", label: "Algeria", phone: "213" },
        { code: "EC", label: "Ecuador", phone: "593" },
        { code: "EE", label: "Estonia", phone: "372" },
        { code: "EG", label: "Egypt", phone: "20" },
        { code: "EH", label: "Western Sahara", phone: "212" },
        { code: "ER", label: "Eritrea", phone: "291" },
        { code: "ES", label: "Spain", phone: "34" },
        { code: "ET", label: "Ethiopia", phone: "251" },
        { code: "FI", label: "Finland", phone: "358" },
        { code: "FJ", label: "Fiji", phone: "679" },
        {
            code: "FK",
            label: "Falkland Islands (Malvinas)",
            phone: "500",
        },
        {
            code: "FM",
            label: "Micronesia, Federated States of",
            phone: "691",
        },
        { code: "FO", label: "Faroe Islands", phone: "298" },
        {
            code: "FR",
            label: "France",
            phone: "33",
            suggested: true,
        },
        { code: "GA", label: "Gabon", phone: "241" },
        { code: "GB", label: "United Kingdom", phone: "44" },
        { code: "GD", label: "Grenada", phone: "1-473" },
        { code: "GE", label: "Georgia", phone: "995" },
        { code: "GF", label: "French Guiana", phone: "594" },
        { code: "GG", label: "Guernsey", phone: "44" },
        { code: "GH", label: "Ghana", phone: "233" },
        { code: "GI", label: "Gibraltar", phone: "350" },
        { code: "GL", label: "Greenland", phone: "299" },
        { code: "GM", label: "Gambia", phone: "220" },
        { code: "GN", label: "Guinea", phone: "224" },
        { code: "GP", label: "Guadeloupe", phone: "590" },
        { code: "GQ", label: "Equatorial Guinea", phone: "240" },
        { code: "GR", label: "Greece", phone: "30" },
        {
            code: "GS",
            label: "South Georgia and the South Sandwich Islands",
            phone: "500",
        },
        { code: "GT", label: "Guatemala", phone: "502" },
        { code: "GU", label: "Guam", phone: "1-671" },
        { code: "GW", label: "Guinea-Bissau", phone: "245" },
        { code: "GY", label: "Guyana", phone: "592" },
        { code: "HK", label: "Hong Kong", phone: "852" },
        {
            code: "HM",
            label: "Heard Island and McDonald Islands",
            phone: "672",
        },
        { code: "HN", label: "Honduras", phone: "504" },
        { code: "HR", label: "Croatia", phone: "385" },
        { code: "HT", label: "Haiti", phone: "509" },
        { code: "HU", label: "Hungary", phone: "36" },
        { code: "ID", label: "Indonesia", phone: "62" },
        { code: "IE", label: "Ireland", phone: "353" },
        { code: "IL", label: "Israel", phone: "972" },
        { code: "IM", label: "Isle of Man", phone: "44" },
        { code: "IN", label: "India", phone: "91" },
        {
            code: "IO",
            label: "British Indian Ocean Territory",
            phone: "246",
        },
        { code: "IQ", label: "Iraq", phone: "964" },
        {
            code: "IR",
            label: "Iran, Islamic Republic of",
            phone: "98",
        },
        { code: "IS", label: "Iceland", phone: "354" },
        { code: "IT", label: "Italy", phone: "39" },
        { code: "JE", label: "Jersey", phone: "44" },
        { code: "JM", label: "Jamaica", phone: "1-876" },
        { code: "JO", label: "Jordan", phone: "962" },
        {
            code: "JP",
            label: "Japan",
            phone: "81",
            suggested: true,
        },
        { code: "KE", label: "Kenya", phone: "254" },
        { code: "KG", label: "Kyrgyzstan", phone: "996" },
        { code: "KH", label: "Cambodia", phone: "855" },
        { code: "KI", label: "Kiribati", phone: "686" },
        { code: "KM", label: "Comoros", phone: "269" },
        {
            code: "KN",
            label: "Saint Kitts and Nevis",
            phone: "1-869",
        },
        {
            code: "KP",
            label: "Korea, Democratic People's Republic of",
            phone: "850",
        },
        { code: "KR", label: "Korea, Republic of", phone: "82" },
        { code: "KW", label: "Kuwait", phone: "965" },
        { code: "KY", label: "Cayman Islands", phone: "1-345" },
        { code: "KZ", label: "Kazakhstan", phone: "7" },
        {
            code: "LA",
            label: "Lao People's Democratic Republic",
            phone: "856",
        },
        { code: "LB", label: "Lebanon", phone: "961" },
        { code: "LC", label: "Saint Lucia", phone: "1-758" },
        { code: "LI", label: "Liechtenstein", phone: "423" },
        { code: "LK", label: "Sri Lanka", phone: "94" },
        { code: "LR", label: "Liberia", phone: "231" },
        { code: "LS", label: "Lesotho", phone: "266" },
        { code: "LT", label: "Lithuania", phone: "370" },
        { code: "LU", label: "Luxembourg", phone: "352" },
        { code: "LV", label: "Latvia", phone: "371" },
        { code: "LY", label: "Libya", phone: "218" },
        { code: "MA", label: "Morocco", phone: "212" },
        { code: "MC", label: "Monaco", phone: "377" },
        {
            code: "MD",
            label: "Moldova, Republic of",
            phone: "373",
        },
        { code: "ME", label: "Montenegro", phone: "382" },
        {
            code: "MF",
            label: "Saint Martin (French part)",
            phone: "590",
        },
        { code: "MG", label: "Madagascar", phone: "261" },
        { code: "MH", label: "Marshall Islands", phone: "692" },
        {
            code: "MK",
            label: "Macedonia, the Former Yugoslav Republic of",
            phone: "389",
        },
        { code: "ML", label: "Mali", phone: "223" },
        { code: "MM", label: "Myanmar", phone: "95" },
        { code: "MN", label: "Mongolia", phone: "976" },
        { code: "MO", label: "Macao", phone: "853" },
        {
            code: "MP",
            label: "Northern Mariana Islands",
            phone: "1-670",
        },
        { code: "MQ", label: "Martinique", phone: "596" },
        { code: "MR", label: "Mauritania", phone: "222" },
        { code: "MS", label: "Montserrat", phone: "1-664" },
        { code: "MT", label: "Malta", phone: "356" },
        { code: "MU", label: "Mauritius", phone: "230" },
        { code: "MV", label: "Maldives", phone: "960" },
        { code: "MW", label: "Malawi", phone: "265" },
        { code: "MX", label: "Mexico", phone: "52" },
        { code: "MY", label: "Malaysia", phone: "60" },
        { code: "MZ", label: "Mozambique", phone: "258" },
        { code: "NA", label: "Namibia", phone: "264" },
        { code: "NC", label: "New Caledonia", phone: "687" },
        { code: "NE", label: "Niger", phone: "227" },
        { code: "NF", label: "Norfolk Island", phone: "672" },
        { code: "NG", label: "Nigeria", phone: "234" },
        { code: "NI", label: "Nicaragua", phone: "505" },
        { code: "NL", label: "Netherlands", phone: "31" },
        { code: "NO", label: "Norway", phone: "47" },
        { code: "NP", label: "Nepal", phone: "977" },
        { code: "NR", label: "Nauru", phone: "674" },
        { code: "NU", label: "Niue", phone: "683" },
        { code: "NZ", label: "New Zealand", phone: "64" },
        { code: "OM", label: "Oman", phone: "968" },
        { code: "PA", label: "Panama", phone: "507" },
        { code: "PE", label: "Peru", phone: "51" },
        { code: "PF", label: "French Polynesia", phone: "689" },
        { code: "PG", label: "Papua New Guinea", phone: "675" },
        { code: "PH", label: "Philippines", phone: "63" },
        { code: "PK", label: "Pakistan", phone: "92" },
        { code: "PL", label: "Poland", phone: "48" },
        {
            code: "PM",
            label: "Saint Pierre and Miquelon",
            phone: "508",
        },
        { code: "PN", label: "Pitcairn", phone: "870" },
        { code: "PR", label: "Puerto Rico", phone: "1" },
        {
            code: "PS",
            label: "Palestine, State of",
            phone: "970",
        },
        { code: "PT", label: "Portugal", phone: "351" },
        { code: "PW", label: "Palau", phone: "680" },
        { code: "PY", label: "Paraguay", phone: "595" },
        { code: "QA", label: "Qatar", phone: "974" },
        { code: "RE", label: "Reunion", phone: "262" },
        { code: "RO", label: "Romania", phone: "40" },
        { code: "RS", label: "Serbia", phone: "381" },
        { code: "RU", label: "Russian Federation", phone: "7" },
        { code: "RW", label: "Rwanda", phone: "250" },
        { code: "SA", label: "Saudi Arabia", phone: "966" },
        { code: "SB", label: "Solomon Islands", phone: "677" },
        { code: "SC", label: "Seychelles", phone: "248" },
        { code: "SD", label: "Sudan", phone: "249" },
        { code: "SE", label: "Sweden", phone: "46" },
        { code: "SG", label: "Singapore", phone: "65" },
        { code: "SH", label: "Saint Helena", phone: "290" },
        { code: "SI", label: "Slovenia", phone: "386" },
        {
            code: "SJ",
            label: "Svalbard and Jan Mayen",
            phone: "47",
        },
        { code: "SK", label: "Slovakia", phone: "421" },
        { code: "SL", label: "Sierra Leone", phone: "232" },
        { code: "SM", label: "San Marino", phone: "378" },
        { code: "SN", label: "Senegal", phone: "221" },
        { code: "SO", label: "Somalia", phone: "252" },
        { code: "SR", label: "Suriname", phone: "597" },
        { code: "SS", label: "South Sudan", phone: "211" },
        {
            code: "ST",
            label: "Sao Tome and Principe",
            phone: "239",
        },
        { code: "SV", label: "El Salvador", phone: "503" },
        {
            code: "SX",
            label: "Sint Maarten (Dutch part)",
            phone: "1-721",
        },
        {
            code: "SY",
            label: "Syrian Arab Republic",
            phone: "963",
        },
        { code: "SZ", label: "Swaziland", phone: "268" },
        {
            code: "TC",
            label: "Turks and Caicos Islands",
            phone: "1-649",
        },
        { code: "TD", label: "Chad", phone: "235" },
        {
            code: "TF",
            label: "French Southern Territories",
            phone: "262",
        },
        { code: "TG", label: "Togo", phone: "228" },
        { code: "TH", label: "Thailand", phone: "66" },
        { code: "TJ", label: "Tajikistan", phone: "992" },
        { code: "TK", label: "Tokelau", phone: "690" },
        { code: "TL", label: "Timor-Leste", phone: "670" },
        { code: "TM", label: "Turkmenistan", phone: "993" },
        { code: "TN", label: "Tunisia", phone: "216" },
        { code: "TO", label: "Tonga", phone: "676" },
        { code: "TR", label: "Turkey", phone: "90" },
        {
            code: "TT",
            label: "Trinidad and Tobago",
            phone: "1-868",
        },
        { code: "TV", label: "Tuvalu", phone: "688" },
        {
            code: "TW",
            label: "Taiwan, Republic of China",
            phone: "886",
        },
        {
            code: "TZ",
            label: "United Republic of Tanzania",
            phone: "255",
        },
        { code: "UA", label: "Ukraine", phone: "380" },
        { code: "UG", label: "Uganda", phone: "256" },
        {
            code: "US",
            label: "United States",
            phone: "1",
            suggested: true,
        },
        { code: "UY", label: "Uruguay", phone: "598" },
        { code: "UZ", label: "Uzbekistan", phone: "998" },
        {
            code: "VA",
            label: "Holy See (Vatican City State)",
            phone: "379",
        },
        {
            code: "VC",
            label: "Saint Vincent and the Grenadines",
            phone: "1-784",
        },
        { code: "VE", label: "Venezuela", phone: "58" },
        {
            code: "VG",
            label: "British Virgin Islands",
            phone: "1-284",
        },
        {
            code: "VI",
            label: "US Virgin Islands",
            phone: "1-340",
        },
        { code: "VN", label: "Vietnam", phone: "84" },
        { code: "VU", label: "Vanuatu", phone: "678" },
        { code: "WF", label: "Wallis and Futuna", phone: "681" },
        { code: "WS", label: "Samoa", phone: "685" },
        { code: "XK", label: "Kosovo", phone: "383" },
        { code: "YE", label: "Yemen", phone: "967" },
        { code: "YT", label: "Mayotte", phone: "262" },
        { code: "ZA", label: "South Africa", phone: "27" },
        { code: "ZM", label: "Zambia", phone: "260" },
        { code: "ZW", label: "Zimbabwe", phone: "263" },
    ],

    DOWN_PAYMENT_OPTIONS: [
        { id: 1, name: "No prepayment" },
        { id: 2, name: "Percentage of total price (without cleaning)" },
        { id: 3, name: "Percentage from total price" },
        { id: 4, name: "Fixed amount per day" },
        { id: 5, name: "Flat amount per stay" },
    ],
    SECURITY_DEPOSIT_OPTIONS: [
        { id: 1, name: "No deposit" },
        { id: 2, name: "Percentage of total price (without cleaning)" },
        { id: 3, name: "Percentage from total price" },
        { id: 4, name: "Fixed amount per day" },
        { id: 5, name: "Flat amount per stay" },
    ],
    FEE_AND_TAX: {
        Fee: {
            "Air conditioning fee": "Air conditioning fee",
            "Airbnb Short Term Cleaning Fee": "Airbnb Short Term Cleaning Fee",
            "Book Direct service fee": "Book Direct service fee",
            "Booking fee": "Booking fee",
            "Children extra fee": "Children extra fee",
        },
        Tax: {
            "City tax": "City tax",
            "Local tax": "Local tax",
            "Tourist tax": "Tourist tax",
            "VAT": "VAT"
        },
    },
    FEE_AND_TAX_CALCULATION_TYPES: [
        { id: "Percentage", name: "Percentage" },
        { id: "Percentage per day", name: "Percentage per day" },
        { id: "Percentage per person", name: "Percentage per person" },
        { id: "Amount per stay", name: "Amount per stay" },
        { id: "Amount per night", name: "Amount per night" },
        { id: "Amount per person & stay", name: "Amount per person & stay" },
        { id: "Amount per person & week", name: "Amount per person & week" },
        { id: "Amount per week", name: "Amount per week" }
    ],
    COLLECTIVE_TYPES: [
        { id: "Upon booking", name: "Upon booking" },
        { id: "Upon arrival", name: "Upon arrival" }
    ],
    COLLECTIVE_TYPES: [
        { id: "Upon booking", name: "Upon booking" },
        { id: "Upon arrival", name: "Upon arrival" }
    ],
    CHECKIN_FROM: {
        "at the property": "at the property"
    },
    LATE_IN_EARLY_OUT_FEES: {
        0: "Early Check-in",
        1: "Late Check-out"
    },
    AMENITIES_ICONS: {
        "Terrace": "/images/icons/Terrace.svg",
        "Wheelchair access": "/images/icons/Wheelchair access.svg",
        "Parking": "/images/icons/Parking.svg",
    },
    AMENITIES_ICONS: {
        "Hair Dryer": "Hair Dryer.svg",
        "Central Heating": "Central Heating.svg",
        "Washing Machine": "washing-machine.svg",
        "Cable TV": "Cable TV.svg",
        "TV": "TV.svg",
        "internet connection": "Internet connection.svg",
        "Bed Linen": "Bed Linen.svg",
        "Dryer": "Dryer.svg",
        "Billiards / Pool Tables": "Billiards  Pool Tables.svg",
        "Golf": "Golf.svg",
        "No Pets Allowed": "No Pets Allowed.svg",
        "Cross Country Skiing": "Cross Country Skiing.svg",
        "Snowboarding": "Snowboarding.svg",
        "Smoke Detectors": "Smoke Detectors.svg",
        "Parking": "Parking.svg",
        "garage": "garage.svg",
        "Suitable for children": "Suitable for children.svg",
        "Family friendly": "Family friendly.svg",
        "Carbon Monoxide Detector": "Carbon Monoxide Detector.svg",
        "shopping": "shopping.svg",
        "hiking biking nearby": "hiking biking nearby.svg",
        "mountain climbing nearby": "mountain climbing nearby",
        "sledding nearby": "sledding nearby.svg",
        "snowmobiling nearby": "snowmobiling nearby.svg",
        "Smoking not allowed": "Smoking not allowed.svg",
        "Disinfectants used for cleaning": "Disinfectants used for cleaning.svg",
        "Contactless check-in and checkout is available.": "Contactless check-in and checkout is available.svg",
        "Living room": "Living room.svg",
        "Fireplace": "Fireplace.svg",
        "Towels": "Towels.svg",
        "Dishwasher": "Dishwasher.svg",
        "kettle": "kettle.svg",
        "Cookware  Kitchen Utensils": "Cookware  Kitchen Utensils.svg",
        "cooking hob": "cooking hob.svg",
        "oven": "oven.svg",
        "microwave": "microwave.svg",
        "toaster": "toaster.svg",
        "fridge / freezer": "fridge  freezer.svg",
        "freezer": "freezer.svg",
        "air conditioning": "air conditioning.svg",
        "sofa": "sofa.svg",
        "stove": "stove.svg",
        "Free Wireless Internet": "Free Wireless Internet.svg",
        "Ice Maker": "Ice Maker.svg",
        "blender": "blender.svg",
        "Ironing Board": "Ironing Board.svg",
        "Pets are welcome": "Pets are welcome.svg",
        "Heating": "Heating.svg",
        "Outdoor Parking": "Outdoor Parking.svg",
        "Waterfront": "Waterfront.svg",
        "Near ocean": "Near ocean.svg",
        "Laptop workspace": "Laptop workspace.svg",
        "Gym": "gym.svg",
        "No parties": "No parties.svg",
        "Water View": "Water View.svg",
        "Fire Extinguisher": "Fire Extinguisher.svg",
        "outdoor furniture": "outdoor furniture.svg",
        "Property is vacant for at least 24 hours between reservations.": "Property is vacant for at least 24 hours between reservations.svg",
        "Ceiling Fan": "Ceiling Fan.svg",
        "Coffee Maker in Room": "coffee-machine.svg",
        "Elevator": "Elevator.svg",
        "Free Parking": "Free Parking.svg",
        "No Smoking Rooms/Facilities": "No Smoking RoomsFacilities.svg",
        "garden": "garden.svg",
        "river": "river.svg",
        "Downtown": "Downtown.svg",
        "private entrance": "private entrance.svg",
        "Drying Rack": "Drying Rack.svg",
        "Balcony": "Balcony.svg",
        "Terrace": "Terrace.svg",
        "gas/electric hob": "gas electric hob.svg",
        "radio": "radio.svg",
        "swimming pool": "swimming pool.svg",
        "BBQ grill": "BBQ grill.svg",
        "High speed Internet access": "High speed Internet access.svg",
        "dining room": "dining room.svg",
        "chairs": "chairs.svg",
        "Restaurant": "Restaurant.svg",
        "Boating": "Boating.svg",
        "Fishing": "Fishing.svg",
        "Free Local Telephone Calls": "Free Local Telephone Calls.svg",
        "Heated Pool": "Heated Pool.svg",
        "Outdoor Pool": "Outdoor Pool.svg",
        "Shopping Mall": "Shopping Mall.svg",
        "Outdoor Tennis": "Outdoor Tennis.svg",
        "Local hospital": "Local hospital.svg",
        "Smart TV": "Smart TV.svg",
        "Patio": "Patio.svg",
        "External Lighting": "External Lighting.svg",
        "beach towels": "beach towels.svg",
        "Iron  Ironing Board": "Iron  Ironing Board.svg",
        "Bed Linen  Towels": "Bed Linen  Towels.svg",
        "High Chairs": "High Chairs.svg",
        "single bed": "single bed.svg",
        "Queen size bed": "Queen size bed.svg",
        "Private parking": "Private parking.svg",
        "Wireless Internet": "Wireless Internet.svg",
        "Communal pool": "Communal pool.svg",
        "full kitchen": "full kitchen.svg",
        "Hot Tub": "Hot Tub.svg",
        "Game room": "Game room.svg",
        "Concierge": "Concierge.svg",
        "Mountain View": "Mountain View.svg",
        "Spa": "Spa.svg",
        "Massage": "Massage.svg",
        "Private pool": "Private pool.svg",
        "Breakfast booking possible": "Breakfast booking possible.svg",
        "Veranda": "Veranda.svg",
        "Housekeeping service": "Housekeeping service.svg",
        "leisure gambling": "leisure gambling.svg",
        "first aid kit": "first aid kit.svg",
        "accommodations other services car available": "accommodations other services car available.svg",
        "Enhanced cleaning practices": "Enhanced cleaning practices.svg",
        "Linen and towels washed in at least 60°C/140°F": "Linen and towels washed.svg",
        "Stereo": "Stereo.svg",
        "Fitness Room": "Fitness Room.svg",
        "Sauna": "Sauna.svg",
        "wifi": "wifi.svg",
        "pool": "pool.svg",
        "Iron": "Iron.svg",
        "Doorman": "Doorman.svg",
        "Refrigerator": "Refrigerator.svg",
        "Family/kids friendly": "Family/kids friendly",
        "location beachfront": "location beachfront.svg",
        "High touch surfaces disinfected": "High touch surfaces disinfected.svg",
        "washer - common space": "washer - common space.svg",
        "dryer - common space": "dryer - common space.svg",
        "Kitchen": "Kitchen.svg",
        "coffee maker": "coffee maker.svg",
        "Crockery  Cutlery": "Crockery  Cutlery.svg",
        "Internet": "Internet.svg",
        "Packing": "Packing.svg",
        "Baby cot": "Baby cot.svg",
        "Swimming Pool": "Swimming Pool-2.svg",
        "Washing machine": "Washing machine.svg",
        "Linen & towels": "Linen & towels.svg",
        "Satellite TV": "Satellite TV.svg",
        "Garden": "Garden2.svg",
        "Iron and Ironing board": "Ironing Board.svg",
        "Air Conditioning": "air-conditioner.svg"
    },
    LANGUAGES_SPOKEN: {
        English: "English",
        Spanish: "Spanish",
        French: "French",
        Mandarin: "Mandarin",
        Hindi: "Hindi",
        Arabic: "Arabic",
        Russian: "Russian",
        Swahili: "Swahili",
        Japanese: "Japanese",
        Korean: "Korean",
        Portuguese: "Portuguese",
        German: "German",
        Italian: "Italian",
        Turkish: "Turkish",
        Urdu: "Urdu",
        Bengali: "Bengali",
        Indonesian: "Indonesian",
        Vietnamese: "Vietnamese",
        Thai: "Thai",
        Hebrew: "Hebrew",
        Persian: "Persian",
        Greek: "Greek",
        Zulu: "Zulu",
        Hausa: "Hausa",
        Yoruba: "Yoruba",
        Tamil: "Tamil",
        Tagalog: "Tagalog",
        Malay: "Malay",
        Pashto: "Pashto",
        Nepali: "Nepali",
        Maori: "Maori",
        Icelandic: "Icelandic",
        Finnish: "Finnish",
        Hungarian: "Hungarian",
        Polish: "Polish",
        Czech: "Czech",
        Ukrainian: "Ukrainian",
        Kurdish: "Kurdish",
        Swedish: "Swedish",
        Danish: "Danish",
        Norwegian: "Norwegian",
        Dutch: "Dutch",
        Afrikaans: "Afrikaans",
        Amharic: "Amharic",
        Somali: "Somali",
        Cherokee: "Cherokee",
        Navajo: "Navajo",
        Hawaiian: "Hawaiian",
        Samoan: "Samoan",
        Fijian: "Fijian",
        Tahitian: "Tahitian",
        Māori: "Māori",
        Tongan: "Tongan",
        Rapa_Nui: "Rapa_Nui",
        Inuktitut: "Inuktitut",
        Cree: "Cree",
        Ojibwe: "Ojibwe",
        Quechua: "Quechua",
        Guarani: "Guarani",
        Mapudungun: "Mapudungun",
        Nahuatl: "Nahuatl",
        Lakota: "Lakota",
        Hopi: "Hopi",
        Yuchi: "Yuchi",
        Khoisan: "Khoisan",
        Khoekhoe: "Khoekhoe",
        Basque: "Basque",
        Catalan: "Catalan",
        Galician: "Galician",
        Welsh: "Welsh",
        Irish: "Irish",
        Manx: "Manx",
        Luxembourgish: "Luxembourgish",
        Maltese: "Maltese",
        Sinhala: "Sinhala",
        Dhivehi: "Dhivehi",
        Burmese: "Burmese",
        Khmer: "Khmer",
        Lao: "Lao",
        Mongolian: "Mongolian",
        Tibetan: "Tibetan",
        Uighur: "Uighur",
        Kazakh: "Kazakh",
        Kyrgyz: "Kyrgyz",
        Tajik: "Tajik",
        Turkmen: "Turkmen",
        Uzbek: "Uzbek",
        Aymara: "Aymara",
        Mapuche: "Mapuche",
        Yoruba: "Yoruba",
        Igbo: "Igbo",
        Hausa: "Hausa",
        Shona: "Shona",
        Zulu: "Zulu",
        Xhosa: "Xhosa",
        Oromo: "Oromo",
        Amharic: "Amharic",
        Tigrinya: "Tigrinya",
        Malagasy: "Malagasy",
        Sesotho: "Sesotho",
        Setswana: "Setswana",
        isiNdebele: "isiNdebele",
        Kinyarwanda: "Ikinyarwanda",
        Kirundi: "Kirundi",
        Luganda: "Luganda",
        Akan: "Akan",
        Twi: "Twi",
        Ga: "Ga",
        Ewe: "Ewe",
        Fante: "Fante",
        Wolof: "Wolof",
        Serer: "Serer",
        Mandinka: "Mandinka",
        Soninke: "Soninke",
        Fulfulde: "Fulfulde",
        Bambara: "Bambara",
        Mossi: "Mossi",
        Moore: "Mòoré",
        Kikuyu: "Kikuyu",
        Luo: "Luo",
        Kinyamwezi: "Kinyamwezi",
        Lugbara: "Lugbara",
        Lugisu: "Lugisu",
        Runyankore: "Runyankore",
        Rukiga: "Rukiga",
        Chichewa: "Chichewa",
        Chewa: "Chewa",
        Nyanja: "Nyanja",
        Tumbuka: "Tumbuka",
        Yao: "Yao",
        Tsonga: "Tsonga",
        Tswana: "Tswana",
        Lozi: "Lozi",
    },
    NATIONALITIES: {
        "Afghan": "Afghan",
        "Albanian": "Albanian",
        "Algerian": "Algerian",
        "American": "American",
        "Andorran": "Andorran",
        "Angolan": "Angolan",
        "Antiguans": "Antiguans",
        "Argentinean": "Argentinean",
        "Armenian": "Armenian",
        "Australian": "Australian",
        "Austrian": "Austrian",
        "Azerbaijani": "Azerbaijani",
        "Bahamian": "Bahamian",
        "Bahraini": "Bahraini",
        "Bangladeshi": "Bangladeshi",
        "Barbadian": "Barbadian",
        "Barbudans": "Barbudans",
        "Batswana": "Batswana",
        "Belarusian": "Belarusian",
        "Belgian": "Belgian",
        "Belizean": "Belizean",
        "Beninese": "Beninese",
        "Bhutanese": "Bhutanese",
        "Bolivian": "Bolivian",
        "Bosnian": "Bosnian",
        "Brazilian": "Brazilian",
        "British": "British",
        "Bruneian": "Bruneian",
        "Bulgarian": "Bulgarian",
        "Burkinabe": "Burkinabe",
        "Burmese": "Burmese",
        "Burundian": "Burundian",
        "Cambodian": "Cambodian",
        "Cameroonian": "Cameroonian",
        "Canadian": "Canadian",
        "Cape Verdean": "Cape Verdean",
        "Central African": "Central African",
        "Chadian": "Chadian",
        "Chilean": "Chilean",
        "Chinese": "Chinese",
        "Colombian": "Colombian",
        "Comoran": "Comoran",
        "Congolese": "Congolese",
        "Costa Rican": "Costa Rican",
        "Croatian": "Croatian",
        "Cuban": "Cuban",
        "Cypriot": "Cypriot",
        "Czech": "Czech",
        "Danish": "Danish",
        "Djibouti": "Djibouti",
        "Dominican": "Dominican",
        "Dutch": "Dutch",
        "East Timorese": "East Timorese",
        "Ecuadorean": "Ecuadorean",
        "Egyptian": "Egyptian",
        "Emirian": "Emirian",
        "Equatorial Guinean": "Equatorial Guinean",
        "Eritrean": "Eritrean",
        "Estonian": "Estonian",
        "Ethiopian": "Ethiopian",
        "Fijian": "Fijian",
        "Filipino": "Filipino",
        "Finnish": "Finnish",
        "French": "French",
        "Gabonese": "Gabonese",
        "Gambian": "Gambian",
        "Georgian": "Georgian",
        "German": "German",
        "Ghanaian": "Ghanaian",
        "Greek": "Greek",
        "Grenadian": "Grenadian",
        "Guatemalan": "Guatemalan",
        "Guinea-Bissauan": "Guinea-Bissauan",
        "Guinean": "Guinean",
        "Guyanese": "Guyanese",
        "Haitian": "Haitian",
        "Herzegovinian": "Herzegovinian",
        "Honduran": "Honduran",
        "Hungarian": "Hungarian",
        "I-Kiribati": "I-Kiribati",
        "Icelander": "Icelander",
        "Indian": "Indian",
        "Indonesian": "Indonesian",
        "Iranian": "Iranian",
        "Iraqi": "Iraqi",
        "Irish": "Irish",
        "Israeli": "Israeli",
        "Italian": "Italian",
        "Ivorian": "Ivorian",
        "Jamaican": "Jamaican",
        "Japanese": "Japanese",
        "Jordanian": "Jordanian",
        "Kazakhstani": "Kazakhstani",
        "Kenyan": "Kenyan",
        "Kittian and Nevisian": "Kittian and Nevisian",
        "Kuwaiti": "Kuwaiti",
        "Kyrgyz": "Kyrgyz",
        "Laotian": "Laotian",
        "Latvian": "Latvian",
        "Lebanese": "Lebanese",
        "Liberian": "Liberian",
        "Libyan": "Libyan",
        "Liechtensteiner": "Liechtensteiner",
        "Lithuanian": "Lithuanian",
        "Luxembourger": "Luxembourger",
        "Macedonian": "Macedonian",
        "Malagasy": "Malagasy",
        "Malawian": "Malawian",
        "Malaysian": "Malaysian",
        "Maldivan": "Maldivan",
        "Malian": "Malian",
        "Maltese": "Maltese",
        "Marshallese": "Marshallese",
        "Mauritanian": "Mauritanian",
        "Mauritian": "Mauritian",
        "Mexican": "Mexican",
        "Micronesian": "Micronesian",
        "Moldovan": "Moldovan",
        "Monacan": "Monacan",
        "Mongolian": "Mongolian",
        "Moroccan": "Moroccan",
        "Mosotho": "Mosotho",
        "Motswana": "Motswana",
        "Mozambican": "Mozambican",
        "Namibian": "Namibian",
        "Nauruan": "Nauruan",
        "Nepali": "Nepali",
        "New Zealander": "New Zealander",
        "Nicaraguan": "Nicaraguan",
        "Nigerian": "Nigerian",
        "Nigerien": "Nigerien",
        "North Korean": "North Korean",
        "Northern Irish": "Northern Irish",
        "Norwegian": "Norwegian",
        "Omani": "Omani",
        "Pakistani": "Pakistani",
        "Palauan": "Palauan",
        "Panamanian": "Panamanian",
        "Papua New Guinean": "Papua New Guinean",
        "Paraguayan": "Paraguayan",
        "Peruvian": "Peruvian",
        "Polish": "Polish",
        "Portuguese": "Portuguese",
        "Qatari": "Qatari",
        "Romanian": "Romanian",
        "Russian": "Russian",
        "Rwandan": "Rwandan",
        "Saint Lucian": "Saint Lucian",
        "Salvadoran": "Salvadoran",
        "Samoan": "Samoan",
        "San Marinese": "San Marinese",
        "Sao Tomean": "Sao Tomean",
        "Saudi": "Saudi",
        "Scottish": "Scottish",
        "Senegalese": "Senegalese",
        "Serbian": "Serbian",
        "Seychellois": "Seychellois",
        "Sierra Leonean": "Sierra Leonean",
        "Singaporean": "Singaporean",
        "Slovakian": "Slovakian",
        "Slovenian": "Slovenian",
        "Solomon Islander": "Solomon Islander",
        "Somali": "Somali",
        "South African": "South African",
        "South Korean": "South Korean",
        "Spanish": "Spanish",
        "Sri Lankan": "Sri Lankan",
        "Sudanese": "Sudanese",
        "Surinamer": "Surinamer",
        "Swazi": "Swazi",
        "Swedish": "Swedish",
        "Swiss": "Swiss",
        "Syrian": "Syrian",
        "Taiwanese": "Taiwanese",
        "Tajik": "Tajik",
        "Tanzanian": "Tanzanian",
        "Thai": "Thai",
        "Togolese": "Togolese",
        "Tongan": "Tongan",
        "Trinidadian/Tobagonian": "Trinidadian/Tobagonian",
        "Tunisian": "Tunisian",
        "Turkish": "Turkish",
        "Tuvaluan": "Tuvaluan",
        "Ugandan": "Ugandan",
        "Ukrainian": "Ukrainian",
        "Uruguayan": "Uruguayan",
        "Uzbekistani": "Uzbekistani",
        "Venezuelan": "Venezuelan",
        "Vietnamese": "Vietnamese",
        "Welsh": "Welsh",
        "Yemenite": "Yemenite",
        "Zambian": "Zambian",
        "Zimbabwean": "Zimbabwean"
    }

}