import dynamic from "next/dynamic";
import FavoritesCss from "../../styles/dashboard/Favorites.module.css";
import Image from "next/image";
import { Container, Table } from "react-bootstrap";
import Delete from "../../../public/images/vector/delete.svg";
import Nextimg from "../../../public/images/vector/next.svg";
import golfhom from "../../../public/images/vector/golfhom.svg";
import Head from "next/head";
import ProtectedRoute from "../../../common components/protected_route";
import React from "react";

const BottomSection = dynamic(
  () => import("../../../common components/bottomGroup"),
  {
    suspense: true,
  }
);
const Favorites = () => {
  return (
    <>
      <ProtectedRoute>
        <Head>
          <title>Ventify | My Favorites</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* BANNER IMAGE FAQ */}
        <div>
          <Image
            fill
            className={FavoritesCss.banner_img}
            src={`${process.env.NEXT_PUBLIC_ASSETS_URL}/images/faq_banner_img.png`}
            alt="faq ventify banner"
          ></Image>
        </div>

        {/*     -------------------------     TEXT AREA      ----------------------------    */}

        <Container>
          <h3 className={FavoritesCss.reservation}>Reservations</h3>

          <h4 className={FavoritesCss.manage}>Manage</h4>

          <Table responsive className={FavoritesCss.bodyRow}>
            <thead className={FavoritesCss.heading}>
              <tr className={FavoritesCss.tableHead}>
                <th className={FavoritesCss.thum}>Thumbnail</th>
                <th className={FavoritesCss.add}>Address</th>
                <th className={FavoritesCss.type}>Type</th>
                <th className={FavoritesCss.price}>Price</th>
                <th className={FavoritesCss.bed}>Bedrooms</th>
                <th className={FavoritesCss.bath}>Baths</th>
                <th className={FavoritesCss.guest}>Guests</th>
                <th className={FavoritesCss.action}>Actions</th>
              </tr>
            </thead>

            <tbody>
              <tr className={FavoritesCss.tableRow}>
                <td>
                  <Image
                    className={FavoritesCss.golfhom}
                    src={golfhom}
                    alt="ventify"
                    fill
                  />
                </td>
                <td>
                  <span className={FavoritesCss.oldTown}>
                    {" "}
                    Old Town’s Farm to Table{" "}
                  </span>
                  6826 E 5th St, Scottsdale, Arizona, United States
                </td>
                <td>Villa</td>
                <td className={FavoritesCss.form}>From $435.69/Night</td>
                <td>4</td>
                <td>3</td>
                <td>10</td>
                <td className={FavoritesCss.twoImage}>
                  <Image
                    src={Delete}
                    alt="Delete"
                    fill
                    className={FavoritesCss.imgChildA}
                  />

                  <Image
                    src={Nextimg}
                    alt="Next Image"
                    fill
                    className={FavoritesCss.imgChildB}
                  />
                </td>
              </tr>
            </tbody>
          </Table>
        </Container>

        {/*  -----------------------------           BOTTOM IMAGE SECTION         ----------------------------  */}

        <BottomSection />
      </ProtectedRoute>
    </>
  );
};

export default Favorites;
